-- #######################################################################################
-- AUTOGENERATED HYPR CONFIG (LUA).
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- This is an example Hyprland config in Lua format.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/

-- You can split this configuration into multiple files
-- Create your files separately and then source them:
-- source = ~/.config/hypr/myColors.conf

-- ################
-- ### MONITORS ###
-- ################

hl.monitor({
  output = "DP-2",
  mode = "3440x1440",
  position = "1920x0",
  scale = 1
})

hl.monitor({
  output = "HDMI-A-1",
  mode = "1920x1080",
  position = "0x500",
  scale = 1
})

-- ###################
-- ### MY PROGRAMS ###
-- ###################

-- https://wiki.hypr.land/Configuring/Keywords/
-- Set programs that you use
local terminal = "kitty"
local fileManager = "thunar"
local menu = "wofi --show drun --allow-images --insensitive --gtk-dark"

-- #################
-- ### AUTOSTART ###
-- #################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch:
-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox

-- exec("waybar")
-- exec("hyprpaper")

-- #############################
-- ### ENVIRONMENT VARIABLES ###
-- #############################

-- https://wiki.hypr.land/Configuring/Environment-variables/
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- #####################
-- ### LOOK AND FEEL ###
-- #####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general
hl.config({
  general = {
    gaps_in = 4,
    gaps_out = 6,
    border_size = 1,
    col = {
      active_border = "rgba(33ccffee) rgba(00ff99ee) 45deg",
      inactive_border = "rgba(595959aa)",
    },
    resize_on_border = false,
    allow_tearing = false,
    layout = "dwindle"
  },

  -- https://wiki.hypr.land/Configuring/Variables/#decoration
  decoration = {
    rounding = 10,
    active_opacity = 1.0,
    inactive_opacity = 1.0,

    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
      color = "rgba(1a1a1aee)"
    }
  },

  -- https://wiki.hypr.land/Configuring/Variables/#blur
  blur = {
    enabled = true,
    size = 3,
    passes = 1,
    vibrancy = 0.1696
  }
})

-- https://wiki.hypr.land/Configuring/Variables/#animations
-- animations = {
--     enabled = true
--
--     -- Default animations, see https://wiki.hypr.land/Configuring/Animations/ for more
--     bezier = "myBezier", "0, 1, 0, 1"
--
--     animation = "windows", "1, 7, myBezier"
--     animation = "windowsOut", "1, 7, default, popin 80%"
--     animation = "border", "1, 10, myBezier"
--     animation = "borderangle", "1, 8, myBezier"
--     animation = "fade", "1, 7, myBezier"
--     animation = "workspaces", "1, 6, myBezier"
--     animation = "specialWorkspace", "1, 6, myBezier"
--     animation = "specialWorkspaceOut", "1, 6, myBezier"
-- }

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
hl.config({
  dwindle = {
    preserve_split = false,
    smart_split = true
  }
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
hl.config({
  master = {
    new_status = "master"
  }
})

-- https://wiki.hypr.land/Configuring/Variables/#misc
hl.config({
  misc = {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
  }
})

-- #############
-- ### INPUT ###
-- #############

-- https://wiki.hypr.land/Configuring/Variables/#input
hl.config(
  {
    input = {
      kb_layout = "us,be",
      kb_options = "grp:lctrl_lwin_toggle",
      repeat_delay = 180,
      repeat_rate = 50,
      follow_mouse = true,
      sensitivity = 0,
      resolve_binds_by_sym = 1,
      numlock_by_default = true,

      touchpad = {
        natural_scroll = false
      }
    }
  })

-- Example per-device config
-- https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
hl.deviced({
  name = "logitech-mx-anywhere-3"
  sensitivity = -0.2
})

-- ###################
-- ### KEYBINDINGS ###
-- ###################

-- See https://wiki.hypr.land/Configuring/Keywords/
-- $mainMod = SUPER # Sets "Windows" key as main modifier
local mainMod = "MOD1"


hl.bind(mainMod .. " + Q", "exec", terminal)
hl.bind(mainMod .. " + C", "killactive", "")
hl.bind(mainMod .. " +  SHIFT + M", "exec", "hyprctl dispatch exit")
hl.bind(mainMod .. " +  SHIFT + S", "exec", "systemctl suspend")
hl.bind(mainMod .. " +  SHIFT + Q", "exec", "shutdown -h now")
hl.bind(mainMod .. " +  CTRL + L", "exec", "hyprlock")
hl.bind(mainMod .. " + E", "exec", fileManager)
hl.bind(mainMod .. " + V", "togglefloating", "")
-- bind(mainMod .." + D", "exec", menu)
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", "pseudo", "# dwindle")
hl.bind(mainMod .. " + G", "layoutmsg", "togglesplit")

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H", "movefocus", "l")
hl.bind(mainMod .. " + L", "movefocus", "r")
hl.bind(mainMod .. " + K", "movefocus", "u")
hl.bind(mainMod .. " + J", "movefocus", "d")

-- Swap window with mainMod + arrow keys
hl.bind(mainMod .. " +  SHIFT, H", "swapwindow", "l")
hl.bind(mainMod .. " +  SHIFT, L", "movewindow", "r")
hl.bind(mainMod .. " +  SHIFT, K", "movewindow", "u")
hl.bind(mainMod .. " +  SHIFT, J", "movewindow", "d")

-- Move workspace to monitor
hl.bind(mainMod .. " + , X", "movecurrentworkspacetomonitor", "0")
hl.bind(mainMod .. " + , Z", "movecurrentworkspacetomonitor", "1")

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", "workspace", "1")
hl.bind(mainMod .. " + 2", "workspace", "2")
hl.bind(mainMod .. " + 3", "workspace", "3")
hl.bind(mainMod .. " + 4", "workspace", "4")
hl.bind(mainMod .. " + 5", "workspace", "5")
hl.bind(mainMod .. " + 6", "workspace", "6")
hl.bind(mainMod .. " + 7", "workspace", "7")
hl.bind(mainMod .. " + 8", "workspace", "8")
hl.bind(mainMod .. " + 9", "workspace", "9")
hl.bind(mainMod .. " + 0", "workspace", "10")

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " +  SHIFT + 1", "movetoworkspacesilent", "1")
hl.bind(mainMod .. " +  SHIFT + 2", "movetoworkspacesilent", "2")
hl.bind(mainMod .. " +  SHIFT + 3", "movetoworkspacesilent", "3")
hl.bind(mainMod .. " +  SHIFT + 4", "movetoworkspacesilent", "4")
hl.bind(mainMod .. " +  SHIFT + 5", "movetoworkspacesilent", "5")
hl.bind(mainMod .. " +  SHIFT + 6", "movetoworkspacesilent", "6")
hl.bind(mainMod .. " +  SHIFT + 7", "movetoworkspacesilent", "7")
hl.bind(mainMod .. " +  SHIFT + 8", "movetoworkspacesilent", "8")
hl.bind(mainMod .. " +  SHIFT + 9", "movetoworkspacesilent", "9")
hl.bind(mainMod .. " +  SHIFT + 0", "movetoworkspacesilent", "10")

hl.bind(mainMod .. " + F", "fullscreen", "0")

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + , mouse_down", "workspace", "e+1")
hl.bind(mainMod .. " + , mouse_up", "workspace", "e-1")

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + , mouse:272", "movewindow", "")
hl.bind(mainMod .. " + , mouse:273", "resizewindow", "")

-- Laptop multimedia keys for volume and LCD brightness
-- bindel("", "XF86AudioRaiseVolume", "exec", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+") bindel("", "XF86AudioLowerVolume", "exec", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")
-- bindel("", "XF86AudioMute", "exec", "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")
-- bindel("", "XF86AudioMicMute", "exec", "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle")
-- bindel("", "XF86MonBrightnessUp", "exec", "brightnessctl s 10%+")
-- bindel("", "XF86MonBrightnessDown", "exec", "brightnessctl s 10%-")

-- Requires playerctl
-- bindl("", "XF86AudioNext", "exec", "playerctl next")
-- bindl("", "XF86AudioPause", "exec", "playerctl play-pause")
-- bindl("", "XF86AudioPlay", "exec", "playerctl play-pause")
-- bindl("", "XF86AudioPrev", "exec", "playerctl previous")

-- Misc
-- bind("Ctrl+Alt, W", "exec", "killall waybar || waybar")
-- bind("", "Print", "exec", "grim -g \"$(slurp)\"")

-- ##############################
-- ### WINDOWS AND WORKSPACES ###
-- ##############################

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/


-- exec("[workspace 1 silent] kitty")
-- exec("[workspace 9 silent] flatpak run com.slack.Slack")
-- exec("[workspace 8 silent] com.google.Chrome")
--
-- -- Keybinds for scratchpads
-- bind(mainMod .." +  T", "togglespecialworkspace", "thunarpad")
-- bind(mainMod .." +  S", "togglespecialworkspace", "spotipad")
-- bind(mainMod .." +  B", "togglespecialworkspace", "debug")
--
-- -- Autostart Thunar in the special workspace (optional)
-- exec("[workspace special:spotipad silent] spotify-launcher --class spotipad")
