# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/#setting-wallpapers

wallpaper  {
  monitor = DP-1
  path = ~/Pictures/wallpapers/21-9/onepiece.png
}

wallpaper  {
  monitor = DP-2
  path = ~/Pictures/wallpapers/21-9/onepiece.png
}

wallpaper  {
  monitor = HDMI-A-2
  path = ~/Pictures/wallpapers/16-9/hyprminlogo.png
}

splash = false
force_default_wallpaper = -1
disable_hyprland_logo = true
