# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/#setting-wallpapers

wallpaper  {
  monitor =DP-2
  path = ~/Pictures/wallpapers/archgirl.png
}

wallpaper  {
  monitor = HDMI-A-1
  path = ~/Pictures/wallpapers/hyprminlogo.png
}
